# --- Project Identification ---
sonar.projectKey=noteApp
sonar.projectName=noteApp
sonar.projectVersion=1.0

# --- Source Directories ---
sonar.sources=backend,frontend/vite-project/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

# --- Encoding ---
sonar.sourceEncoding=UTF-8

# --- SonarQube Server ---
sonar.host.url=http://localhost:9000

# --- Authentication ---
sonar.login=sqp_0f51f3e577c7d87f3fdf2965a87f780b72782dd6
